vanillaes/absurdum

- README.md
- docs/arrays/find.md
- src/arrays/find.js
- src/arrays/find.spec.js
- src/arrays/index.d.ts
- src/arrays/index.js
> add array find

- README.md
- src/arrays/every.js
- src/arrays/every.spec.js
- src/arrays/index.d.ts
- src/arrays/index.js
> add array every

- README.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/zip.js
- src/arrays/zip.spec.js
> add array zip method, docs, tests

- README.md
- src/strings/includes.js
- src/strings/includes.spec.js
- src/strings/index.d.ts
- src/strings/index.js
> added string includes

- README.md
- src/arrays/index.js
- src/arrays/unique.js
- src/arrays/unique.spec.js
> Add arrays.unique

- README.md
- src/objects/exclude.js
- src/objects/exclude.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> add objects.exclude

- README.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/take.js
- src/arrays/take.spec.js
> add arrays.take

- README.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/indexOf.js
- src/strings/indexOf.spec.js
> add strings.indexOf method, docs, tests

- README.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/union.js
- src/arrays/union.spec.js
> arrays.union method, docs, tests

- src/objects/exclude.js
- src/objects/include.js
> improved include and exclude as suggested

- README.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/join.js
- src/arrays/join.spec.js
> add arrays.join

- README.md
- dist/absurdum.cjs.js
- dist/absurdum.esm.js
- docs/arrays/slice.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/slice.d.ts
- src/arrays/slice.js
- src/arrays/slice.spec.js
> add arrays.slice

- README.md
- dist/absurdum.cjs.js
- dist/absurdum.esm.js
- docs/arrays/pull.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/pull.d.ts
- src/arrays/pull.js
- src/arrays/pull.spec.js
> add arrays.pull

- src/arrays/compact.js
The initial implementation was unnecessarily complex. Not sure what I was thinking ¯\\_(ツ)_/¯
> simplify arrays.compact

- src/arrays/flat.js
- src/arrays/flat.spec.js
> update arrays.flat to recursively implement spec

- README.md
- src/strings/chomp.js
- src/strings/chomp.spec.js
- src/strings/index.d.ts
- src/strings/index.js
> add strings.chomp method, docs, tests

- README.md
- dist/absurdum.cjs.js
- dist/absurdum.esm.js
- docs/arrays/lastIndexOf.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/lastIndexOf.d.ts
- src/arrays/lastIndexOf.js
- src/arrays/lastIndexOf.spec.js
> add arrays.lastIndexOf

- README.md
- src/arrays/flatten.js
- src/arrays/flatten.spec.js
- src/arrays/index.d.ts
- src/arrays/index.js
> arrays flatten method, docs, tests

- README.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/keys.js
- src/objects/keys.spec.js
> objects.keys method, docs, tests

- src/objects/invert.spec.js
> add missing brackets and update incorrect values in tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/arrays/frequency.md
- src/arrays/frequency.d.ts
- src/arrays/frequency.js
- src/arrays/frequency.spec.js
- src/arrays/index.d.ts
- src/arrays/index.js
> add arr-frequency method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/pick.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/pick.d.ts
- src/objects/pick.js
- src/objects/pick.spec.js
> add objects.pick method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/values.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/values.d.ts
- src/objects/values.js
- src/objects/values.spec.js
> add obj-values method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/at.md
- src/objects/at.d.ts
- src/objects/at.js
- src/objects/at.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> add objects.at method, docs, tests

- src/arrays/tap.js
Closes #120 
tests/lint/types passes 👍 I think I followed the contributing guidelines, but let me know if I missed something
> updated array.tap to use reduce

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/mapKeys.md
- src/objects/index.js
- src/objects/mapKeys.d.ts
- src/objects/mapKeys.js
- src/objects/mapKeys.spec.js
I'm not really sure if I've done the typings/tests properly but I believe its all in passing order
closes #122
> added objects.mapKeys

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/arrays/unzip.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/unzip.d.ts
- src/arrays/unzip.js
- src/arrays/unzip.spec.js
> add arrays unzip method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/merge.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/merge.d.ts
- src/objects/merge.js
- src/objects/merge.spec.js
> add object-merge method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/defaults.md
- src/objects/defaults.d.ts
- src/objects/defaults.js
- src/objects/defaults.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> add obj-defaults method, tests, docs

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/has.md
- src/objects/has.d.ts
- src/objects/has.js
- src/objects/has.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> objects.has method, tests, docs

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/arrays/without.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/without.d.ts
- src/arrays/without.js
- src/arrays/without.spec.js
> array-without method, tests, docs

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/get.md
- src/objects/get.d.ts
- src/objects/get.js
- src/objects/get.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> objects.get method, docs, tests

- README.md
- src/objects/forIn.js
- src/objects/forIn.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> obj-forIn method, tests, docs

- README.md
- src/objects/findLastKey.js
- src/objects/findLastKey.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> findLastKey method, docs, tests

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/arrays/xor.md
- src/arrays/index.d.ts
- src/arrays/index.js
- src/arrays/xor.d.ts
- src/arrays/xor.js
- src/arrays/xor.spec.js
> arr-xor method, tests, docs

- src/objects/forIn.spec.js
- src/objects/mapValues.spec.js
> updated called functions to test as expected

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/result.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/result.d.ts
- src/objects/result.js
- src/objects/result.spec.js
> objects.result method, tests, docs

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/assign.md
- src/objects/assign.d.ts
- src/objects/assign.js
- src/objects/assign.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> objects.assign method, tests, docs

- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/merge.md
- src/objects/merge.d.ts
- src/objects/merge.js
- src/objects/merge.spec.js
> updated merge to match spec, and standardize style with other methods

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/transform.md
- src/objects/index.d.ts
- src/objects/index.js
- src/objects/transform.d.ts
- src/objects/transform.js
- src/objects/transform.spec.js
> obj-transform method, tests, docs

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/objects/defaultsDeep.md
- src/objects/defaultsDeep.d.ts
- src/objects/defaultsDeep.js
- src/objects/defaultsDeep.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> Obj defaultsDeep

- README.md
- dist/absurdum.cjs
- dist/absurdum.esm.js
- docs/strings/camelCase.md
- src/strings/camelCase.d.ts
- src/strings/camelCase.js
- src/strings/camelCase.spec.js
- src/strings/index.d.ts
- src/strings/index.js
> camelCase method, tests, docs

- README.md
- dist/absurdum.cjs
- docs/strings/pascalCase.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/pascalCase.d.ts
- src/strings/pascalCase.js
- src/strings/pascalCase.spec.js
> pascalCase method tests, docs

- README.md
- dist/absurdum.cjs
- docs/strings/snakeCase.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/snakeCase.d.ts
- src/strings/snakeCase.js
- src/strings/snakeCase.spec.js
> snakeCase method, docs, tests

- README.md
- dist/absurdum.cjs
- docs/strings/kebabCase.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/kebabCase.d.ts
- src/strings/kebabCase.js
- src/strings/kebabCase.spec.js
> kebabCase method, docs, tests

- README.md
- src/strings/deburr.js
- src/strings/deburr.spec.js
- src/strings/index.d.ts
- src/strings/index.js
> deburr method, docs, tests

- README.md
- dist/absurdum.cjs
- docs/strings/trimStart.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/trimStart.d.ts
- src/strings/trimStart.js
- src/strings/trimStart.spec.js
> strings.trimStart method, tests, docs

- README.md
- dist/absurdum.cjs
- docs/strings/trimEnd.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/trimEnd.d.ts
- src/strings/trimEnd.js
- src/strings/trimEnd.spec.js
> strings.trimEnd method, tests, docs

- README.md
- dist/absurdum.cjs
- docs/objects/entries.md
- src/objects/entries.d.ts
- src/objects/entries.js
- src/objects/entries.spec.js
- src/objects/index.d.ts
- src/objects/index.js
> objects.entries method, tests, docs

- README.md
- src/strings/index.d.ts
- src/strings/index.js
- src/strings/truncate.js
- src/strings/truncate.spec.js
> truncate method, tests, docs

- README.md
> Update README.md with Operators Table
